// Generated by CoffeeScript 1.7.1
var root;

root = this;

root.augmentApp = angular.module('augmentApp', ['gridster', 'ngRoute', 'ui.bootstrap']);

augmentApp.config(function($routeProvider) {
  return $routeProvider.when('/', {
    templateUrl: 'views/home.html',
    controller: 'ProjectsIndexController'
  }).when('/projects/index', {
    templateUrl: 'views/projects/index.html',
    controller: 'ProjectsIndexController'
  }).when('/projects/:project_key', {
    templateUrl: function(params) {
      return 'views/projects/' + params['project_key'] + '.html';
    },
    controller: 'ProjectsShowController'
  }).when('/press_articles/index', {
    templateUrl: 'views/press_articles/index.html',
    controller: 'PressArticlesIndexController'
  }).when('/contact/form', {
    templateUrl: 'views/contact/form.html',
    controller: 'ContactController'
  }).when('/about/index', {
    templateUrl: 'views/about/index.html',
    controller: 'AboutController'
  }).otherwise({
    redirectTo: '/'
  });
});
