// Generated by CoffeeScript 1.7.1
augmentApp.directive('switchMouseEnter', function() {
  return {
    link: function(scope, element, attrs) {
      var item_description, item_thumbnail;
      item_thumbnail = element.find(".item-thumbnail");
      item_description = element.find(".item-description");
      element.bind("mouseenter", function() {
        item_thumbnail.hide();
        item_description.css('display', 'table');
        return item_description.css('background', scope.getDomainColor(attrs.domain));
      });
      return element.bind("mouseleave", function() {
        item_description.css('display', 'none');
        return item_thumbnail.show();
      });
    }
  };
});
