// Generated by CoffeeScript 1.7.1
augmentApp.factory("AboutFactory", function($q, $http) {
  var about, factory;
  factory = {};
  about = void 0;
  factory.about = function() {
    var deferred;
    deferred = $q.defer();
    $http.get('/data/about.json').then(function(result) {
      return deferred.resolve(result.data);
    });
    return deferred.promise;
  };
  return factory;
});
