// Generated by CoffeeScript 1.7.1
augmentApp.factory("DomainsFactory", function($q, $http) {
  var domains, factory;
  factory = {};
  domains = [];
  factory.index = function() {
    var deferred;
    deferred = $q.defer();
    $http.get('/data/domains.json').then(function(result) {
      return deferred.resolve(result.data);
    });
    return deferred.promise;
  };
  return factory;
});
