// Generated by CoffeeScript 1.7.1
augmentApp.factory("PressArticlesFactory", function($q, $http) {
  var factory, press_articles;
  factory = {};
  press_articles = [];
  factory.index = function() {
    var deferred;
    deferred = $q.defer();
    $http.get('/data/press_articles.json').then(function(result) {
      return deferred.resolve(result.data);
    });
    return deferred.promise;
  };
  return factory;
});
