// Generated by CoffeeScript 1.7.1
(function() {
  augmentApp.controller('AboutController', function($scope, $location, $timeout, $routeParams, ProjectsFactory, AboutFactory, AlertsFactory) {
    return AboutFactory.about().then(function(result) {
      $scope.experiences = result.experiences;
      $scope.distinctions = result.distinctions;
      $scope.formations = result.formations;
      return $scope.skills = result.skills;
    });
  });

}).call(this);
