// Generated by CoffeeScript 1.7.1
augmentApp.controller('PressArticlesIndexController', function($scope, $timeout, PressArticlesFactory, AlertsFactory) {
  PressArticlesFactory.index().then(function(press_articles) {
    return $scope.press_articles = press_articles;
  });
  return $scope.gridsterOpts = {
    columns: 3,
    width: 'auto',
    colWidth: 'auto',
    rowHeight: 'match',
    margins: [10, 10],
    isMobile: true,
    minColumns: 1,
    minRows: 2,
    maxRows: 100,
    defaultSizeX: 2,
    defaultSizeY: 1,
    mobileBreakPoint: 600,
    resizable: {
      enabled: false
    },
    draggable: {
      enabled: true
    }
  };
});
