// Generated by CoffeeScript 1.6.3
(function() {
  augmentApp.controller('UsersController', function($scope, $location, $cookieStore, UsersFactory, AlertsFactory) {
    return $scope.login = function() {
      if (($scope.userName != null) && ($scope.password != null)) {
        return UsersFactory.login($scope.userName, $scope.password).then(function(result) {
          AlertsFactory.addAlert("success", "Successfully logged in");
          $cookieStore.put('user', result);
          return $location.path("/model3ds/index");
        }, function(error) {
          AlertsFactory.addAlert("error", "Incorrect username or password");
          return $location.path("/");
        });
      } else {
        return AlertsFactory.addAlert("error", "Username and password are required");
      }
    };
  });

}).call(this);
